/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;
import view.admin.*; 
import java.awt.CardLayout;
import controller.*;

/**
 *
 * @author Rapjak
 */
public class adminMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminMainFrame.class.getName());

    DashboardPanel pnlDashboard = new DashboardPanel();
    BranchDetailPanel pnlBranchDetail = new BranchDetailPanel(); 
    ComparisonPanel pnlComparison = new ComparisonPanel();
    UserManagementPanel pnlUser = new UserManagementPanel();
    
    public adminMainFrame() {
        initComponents();
        // PASTIKAN mainContentPanel LAYOUTNYA CARDLAYOUT
    // Bisa diset di Properties NetBeans atau via kodingan di sini:
    mainContentPanel.setLayout(new CardLayout());
    
    // Tambahkan Panel-Panel yang sudah diubah jadi JPanel tadi
    mainContentPanel.add(pnlDashboard, "dashboard");
    mainContentPanel.add(pnlBranchDetail, "detail");
    mainContentPanel.add(pnlComparison, "compare");
    mainContentPanel.add(pnlUser, "user");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        btnMenuDashboard = new javax.swing.JButton();
        btnMenuCabang = new javax.swing.JButton();
        btnMenuCompare = new javax.swing.JButton();
        btnMenuUser = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(51, 51, 51));
        menuPanel.setForeground(new java.awt.Color(51, 51, 51));
        menuPanel.setLayout(new java.awt.GridLayout(5, 1));

        btnMenuDashboard.setText("Dashboard");
        btnMenuDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuDashboardActionPerformed(evt);
            }
        });
        menuPanel.add(btnMenuDashboard);

        btnMenuCabang.setText("Detail Cabang");
        btnMenuCabang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCabangActionPerformed(evt);
            }
        });
        menuPanel.add(btnMenuCabang);

        btnMenuCompare.setText("Perbandingan");
        btnMenuCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCompareActionPerformed(evt);
            }
        });
        menuPanel.add(btnMenuCompare);

        btnMenuUser.setText("Manajemen User");
        btnMenuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUserActionPerformed(evt);
            }
        });
        menuPanel.add(btnMenuUser);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        menuPanel.add(btnLogout);

        getContentPane().add(menuPanel, java.awt.BorderLayout.LINE_START);

        mainContentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuDashboardActionPerformed
        CardLayout cl = (CardLayout)(mainContentPanel.getLayout());
        cl.show(mainContentPanel, "dashboard");
        pnlDashboard.refreshData(); // Refresh Data Dashboard
    }//GEN-LAST:event_btnMenuDashboardActionPerformed

    private void btnMenuCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCompareActionPerformed
        CardLayout cl = (CardLayout)(mainContentPanel.getLayout());
    cl.show(mainContentPanel, "compare");
    }//GEN-LAST:event_btnMenuCompareActionPerformed

    private void btnMenuCabangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCabangActionPerformed
        CardLayout cl = (CardLayout)(mainContentPanel.getLayout());
    cl.show(mainContentPanel, "detail");
    }//GEN-LAST:event_btnMenuCabangActionPerformed

    private void btnMenuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUserActionPerformed
        CardLayout cl = (CardLayout)(mainContentPanel.getLayout());
    cl.show(mainContentPanel, "user");
    }//GEN-LAST:event_btnMenuUserActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin Logout?");
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose(); // Tutup jendela Admin
            
            // Buka Login Frame (Asumsi nama file Anda LoginFrame)
            // new view.LoginFrame().setVisible(true); 
            
            // Atau jika belum ada LoginFrame, matikan aplikasi:
            // System.exit(0); 
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    // Method KHUSUS untuk pindah dari Dashboard -> Detail Cabang
    public void openBranchDetail(int idCabang, String namaCabang) {
        pnlBranchDetail.setCabangID(idCabang, namaCabang); // Kirim data ke panel detail
        CardLayout cl = (CardLayout)(mainContentPanel.getLayout());
        cl.show(mainContentPanel, "detail");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminMainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenuCabang;
    private javax.swing.JButton btnMenuCompare;
    private javax.swing.JButton btnMenuDashboard;
    private javax.swing.JButton btnMenuUser;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
