/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

import controller.AdminController;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rapjak
 */
public class BranchDetailPanel extends javax.swing.JPanel {

    AdminController controller = new AdminController();
    int currentCabangID = 0;
    /**
     * Creates new form Branch
     */
    public BranchDetailPanel() {
        initComponents();
    }
    
    // Method ini dipanggil AdminMainFrame
    public void setCabangID(int id, String nama) {
        this.currentCabangID = id;
        lblNamaCabang.setText("Laporan: " + nama);
        refreshTables();
    }
    
    public void refreshTables() {
        if(currentCabangID == 0) return;
        
        // 1. Top Selling
        controller.loadTopSelling(currentCabangID, (DefaultTableModel) tblTopSelling.getModel());
        // 2. Stok Alert
        controller.loadStokByCabang(currentCabangID, (DefaultTableModel) tblStokCabang.getModel());
        // 3. Variance / Selisih
        controller.loadVarianceReport(currentCabangID, (DefaultTableModel) tblVarianceReport.getModel());
        // 4. Menu Management
        controller.loadMenuByCabang(currentCabangID, (DefaultTableModel) tblMenuCabang.getModel());
        // 5. Log Transaksi
        controller.loadLogTransaksi(currentCabangID, (DefaultTableModel) tblLogTransaksi.getModel());
        // Di dalam method refreshTables()
        controller.loadDiskonByCabang(currentCabangID, (DefaultTableModel) tblDiskon.getModel());
        
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTopSelling = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStokCabang = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVarianceReport = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMenuCabang = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDiskon = new javax.swing.JTable();
        setUnavailableButton = new javax.swing.JButton();
        tambahPromoBaruButton = new javax.swing.JButton();
        ubahHargaButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblLogTransaksi = new javax.swing.JTable();
        lblNamaCabang = new javax.swing.JLabel();

        tblTopSelling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Top Menu"
            }
        ));
        jScrollPane1.setViewportView(tblTopSelling);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ringkasan", jPanel1);

        tblStokCabang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Bahan", "Stok Sistem", "Satuan", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblStokCabang);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Stok Saat Ini", jPanel3);

        tblVarianceReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "Bahan", "Stok Sistem", "Stok Fisik", "Selisih", "Alasan", "Barista Pelapor"
            }
        ));
        jScrollPane3.setViewportView(tblVarianceReport);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Laporan Selisih", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Stok & Audit", jPanel2);

        tblMenuCabang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Menu", "Nama Menu", "Kategori", "Ukuran", "Harga Jual", "Status Ketersediaan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblMenuCabang);

        tblDiskon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Diskon", "Nama Promo", "Tipe & Nilai", "Min. Belanja", "Periode Aktif", "Status Aktif"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblDiskon);

        setUnavailableButton.setText("Set Unavailable");
        setUnavailableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setUnavailableButtonActionPerformed(evt);
            }
        });

        tambahPromoBaruButton.setText("Tambah Promo Baru");
        tambahPromoBaruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPromoBaruButtonActionPerformed(evt);
            }
        });

        ubahHargaButton.setText("Ubah Harga");
        ubahHargaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahHargaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(setUnavailableButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ubahHargaButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahPromoBaruButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setUnavailableButton)
                    .addComponent(tambahPromoBaruButton)
                    .addComponent(ubahHargaButton))
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Manajemen Menu", jPanel5);

        tblLogTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Waktu", "ID Trx", "Kasir", "Total Bayar", "Metode Bayar"
            }
        ));
        jScrollPane6.setViewportView(tblLogTransaksi);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Riwayat Transaksi", jPanel6);

        lblNamaCabang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNamaCabang.setText("Laporan Cabang: [Nama Cabang]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(lblNamaCabang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(365, 365, 365))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblNamaCabang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setUnavailableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setUnavailableButtonActionPerformed
        int row = tblMenuCabang.getSelectedRow();
        if (row != -1) {
            int idMenu = (int) tblMenuCabang.getValueAt(row, 0); // Pastikan Kolom 0 itu ID Menu
            boolean currentStatus = (boolean) tblMenuCabang.getValueAt(row, 5); // Kolom 5 itu Status (Checkbox)

            // Toggle (Balik nilai)
            controller.updateMenuStatus(currentCabangID, idMenu, !currentStatus);
            refreshTables();
            JOptionPane.showMessageDialog(this, "Status Menu Diubah!");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih menu dulu!");
        }
    }//GEN-LAST:event_setUnavailableButtonActionPerformed

    private void ubahHargaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahHargaButtonActionPerformed
        int row = tblMenuCabang.getSelectedRow();
        if (row != -1) {
            int idMenu = Integer.parseInt(tblMenuCabang.getValueAt(row, 0).toString());
            String namaMenu = tblMenuCabang.getValueAt(row, 1).toString();
            String hargaLama = tblMenuCabang.getValueAt(row, 4).toString();
            
            String hargaBaruStr = JOptionPane.showInputDialog(this, 
                    "Ubah Harga untuk " + namaMenu + "\nHarga Lama: " + hargaLama, hargaLama);
            
            if (hargaBaruStr != null) {
                try {
                    double hargaBaru = Double.parseDouble(hargaBaruStr);
                    controller.updateMenuPrice(idMenu, hargaBaru);
                    refreshTables(); // Refresh agar tabel update
                    JOptionPane.showMessageDialog(this, "Harga Berhasil Diubah!");
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Input harus angka!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih menu yang mau diubah harganya!");
        }
    }//GEN-LAST:event_ubahHargaButtonActionPerformed

    private void tambahPromoBaruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPromoBaruButtonActionPerformed
        // Membuat Form Input Manual menggunakan JPanel di dalam JOptionPane
        javax.swing.JPanel p = new javax.swing.JPanel(new java.awt.GridLayout(0, 2));
        javax.swing.JTextField txtNama = new javax.swing.JTextField();
        String[] tipe = {"persen", "nominal"};
        javax.swing.JComboBox<String> cbTipe = new javax.swing.JComboBox<>(tipe);
        javax.swing.JTextField txtNilai = new javax.swing.JTextField();
        javax.swing.JTextField txtMin = new javax.swing.JTextField("0");
        javax.swing.JTextField txtStart = new javax.swing.JTextField("2023-01-01");
        javax.swing.JTextField txtEnd = new javax.swing.JTextField("2023-12-31");

        p.add(new javax.swing.JLabel("Nama Promo:")); p.add(txtNama);
        p.add(new javax.swing.JLabel("Tipe:")); p.add(cbTipe);
        p.add(new javax.swing.JLabel("Nilai (Ex: 10 or 5000):")); p.add(txtNilai);
        p.add(new javax.swing.JLabel("Min Belanja:")); p.add(txtMin);
        p.add(new javax.swing.JLabel("Mulai (YYYY-MM-DD):")); p.add(txtStart);
        p.add(new javax.swing.JLabel("Selesai (YYYY-MM-DD):")); p.add(txtEnd);

        int result = JOptionPane.showConfirmDialog(this, p, "Tambah Promo Baru", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            try {
                controller.addDiskon(
                    currentCabangID, 
                    txtNama.getText(),
                    cbTipe.getSelectedItem().toString(),
                    Double.parseDouble(txtNilai.getText()),
                    Double.parseDouble(txtMin.getText()),
                    txtStart.getText(),
                    txtEnd.getText()
                );
                refreshTables();
                JOptionPane.showMessageDialog(this, "Promo Berhasil Ditambahkan!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal! Pastikan format angka dan tanggal benar.");
            }
        }
    }//GEN-LAST:event_tambahPromoBaruButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblNamaCabang;
    private javax.swing.JButton setUnavailableButton;
    private javax.swing.JButton tambahPromoBaruButton;
    private javax.swing.JTable tblDiskon;
    private javax.swing.JTable tblLogTransaksi;
    private javax.swing.JTable tblMenuCabang;
    private javax.swing.JTable tblStokCabang;
    private javax.swing.JTable tblTopSelling;
    private javax.swing.JTable tblVarianceReport;
    private javax.swing.JButton ubahHargaButton;
    // End of variables declaration//GEN-END:variables

}
