/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;
import controller.AdminController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rapjak
 */
public class UserManagementPanel extends javax.swing.JPanel {
    
    AdminController controller = new AdminController();

    /**
     * Creates new form User
     */
    public UserManagementPanel() {
        initComponents();
        refreshUserTable();
        
        // TAMBAHAN: Event saat tabel user diklik
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tblUsers.getSelectedRow();
                if (row != -1) {
                    // Ambil ID User (Kolom 0)
                    int idUser = Integer.parseInt(tblUsers.getValueAt(row, 0).toString());
                    // Panggil Controller untuk isi tabel kanan
                    controller.loadUserActivityLog(idUser, (DefaultTableModel) tblUserLogs.getModel());
                }
            }
        });
    }
    
    private void refreshUserTable() {
        controller.loadUsers((DefaultTableModel) tblUsers.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        tambahUserButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        resetPasswordButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUserLogs = new javax.swing.JTable();

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Role", "Cabang"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        tambahUserButton.setText("Tambah User");
        tambahUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahUserButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        resetPasswordButton.setText("Reset Password");
        resetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Daftar User");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(tambahUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hapusButton)
                        .addGap(112, 112, 112)
                        .addComponent(resetPasswordButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetPasswordButton)
                    .addComponent(hapusButton)
                    .addComponent(tambahUserButton))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Log Aktivitas User Terpilih");

        tblUserLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Waktu", "Aktivitas (Login/Input Stok/Transaksi)", "Keterangan"
            }
        ));
        jScrollPane2.setViewportView(tblUserLogs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(121, 121, 121))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1134, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tambahUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahUserButtonActionPerformed
        // Form Simple Input User (Pakai JOptionPane biar cepat)
        String user = JOptionPane.showInputDialog(this, "Masukkan Username:");
        String pass = JOptionPane.showInputDialog(this, "Masukkan Password:");
        String[] roles = {"admin", "manager", "barista"};
        int roleIdx = JOptionPane.showOptionDialog(this, "Pilih Role", "Role", 0, 3, null, roles, roles[2]);

        if(user != null && pass != null && roleIdx != -1) {
            // Jika Barista, tanya cabang mana
            int idCabang = 0; // 0 = Pusat/Admin
            if(roles[roleIdx].equals("barista")) {
                String idStr = JOptionPane.showInputDialog(this, "Masukkan ID Cabang (Angka):");
                try { idCabang = Integer.parseInt(idStr); } catch (Exception e) {}
            }

            controller.addUser(user, pass, roles[roleIdx], idCabang);
            refreshUserTable();
            JOptionPane.showMessageDialog(this, "User Berhasil Ditambah!");
        }
    }//GEN-LAST:event_tambahUserButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        int row = tblUsers.getSelectedRow();
        if(row != -1) {
            int idUser = (int) tblUsers.getValueAt(row, 0); // Kolom 0 = ID
            int confirm = JOptionPane.showConfirmDialog(this, "Hapus User ini?");
            if(confirm == JOptionPane.YES_OPTION) {
                controller.deleteUser(idUser);
                refreshUserTable();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih user yang mau dihapus!");
        }
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        int row = tblUsers.getSelectedRow();
        if (row != -1) {
            int idUser = Integer.parseInt(tblUsers.getValueAt(row, 0).toString());
            String username = tblUsers.getValueAt(row, 1).toString();

            String newPass = javax.swing.JOptionPane.showInputDialog(this,
                "Masukkan Password Baru untuk " + username + ":");

            if (newPass != null && !newPass.isEmpty()) {
                controller.resetUserPassword(idUser, newPass);
                javax.swing.JOptionPane.showMessageDialog(this, "Password Berhasil Direset!");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih user dulu di tabel kiri!");
        }
    }//GEN-LAST:event_resetPasswordButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton resetPasswordButton;
    private javax.swing.JButton tambahUserButton;
    private javax.swing.JTable tblUserLogs;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
