/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.customer;
import controller.MenuController;
import controller.OrderController;
import model.CartItem;
import model.Menu;
import view.landingPage;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
/**
 *
 * @author Rapjak
 */
public class CustDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustDashboard.class.getName());
    private int idCabang; 
    private ArrayList<CartItem> cartList = new ArrayList<>(); // List Pesanan
    private double grandTotal = 0;
    
    private MenuController menuController = new MenuController();
    private OrderController orderController = new OrderController();
    

    /**
     * Creates new form dashboard
     */
    public CustDashboard() {
        initComponents();
    }
    
    public CustDashboard(int idCabang) {
        this.idCabang = idCabang;
        initComponents();
        
        // 1. SETUP LAYOUT MENU (GRID 2 KOLOM)
        // Sesuai permintaan: 2 Menu Sampingan
        menuPanel.setLayout(new GridLayout(0, 2, 10, 10)); 
        
        // 2. SETUP LAYOUT KERANJANG
        keranjangPanel.setLayout(new BoxLayout(keranjangPanel, BoxLayout.Y_AXIS));
        
        // 3. LOAD DATA & EVENTS
        loadMenuData();
        
        // Fullscreen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kembaliButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        keranjangPanel = new javax.swing.JPanel();
        totalLable = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bungkusComboBox = new javax.swing.JComboBox<>();
        bayarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(78, 52, 46));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AKSATA COFFEE");

        kembaliButton.setBackground(new java.awt.Color(255, 0, 51));
        kembaliButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kembaliButton.setForeground(new java.awt.Color(255, 255, 255));
        kembaliButton.setText("Kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 523, Short.MAX_VALUE)
                .addComponent(kembaliButton)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kembaliButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(menuPanel);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Keranjang");

        javax.swing.GroupLayout keranjangPanelLayout = new javax.swing.GroupLayout(keranjangPanel);
        keranjangPanel.setLayout(keranjangPanelLayout);
        keranjangPanelLayout.setHorizontalGroup(
            keranjangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
        keranjangPanelLayout.setVerticalGroup(
            keranjangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(keranjangPanel);

        totalLable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalLable.setText("Total:");

        jLabel3.setText("Nama Pemesan:");

        bungkusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine In", "Take Away" }));
        bungkusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bungkusComboBoxActionPerformed(evt);
            }
        });

        bayarButton.setBackground(new java.awt.Color(16, 185, 129));
        bayarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bayarButton.setText("Checkout & Bayar");
        bayarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(totalLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namaField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bungkusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bayarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLable)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bungkusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bayarButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadMenuData() {
        menuPanel.removeAll();
        
        // Minta data ke Controller (Controller yang kerja ambil dari DB)
        List<Menu> menus = menuController.getAvailableMenus(idCabang);
        
        // View tinggal menampilkan hasilnya
        for (Menu m : menus) {
            addMenuCard(m);
        }
        
        menuPanel.revalidate();
        menuPanel.repaint();
    }
    
    private void addMenuCard(Menu m) {
        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200,200,200), 1),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        card.setBackground(Color.WHITE);

        JLabel lblNama = new JLabel(m.getName());
        lblNama.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblNama.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        JLabel lblHarga = new JLabel("Rp " + (int)m.getPrice());
        lblHarga.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        JLabel lblKet = new JLabel("<html><center>Klik untuk Detail & Order</center></html>");
        lblKet.setForeground(Color.BLUE);
        lblKet.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblKet.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        // Event Klik
        lblKet.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                showDetailDialog(m);
            }
        });

        card.add(Box.createVerticalStrut(10));
        card.add(lblNama);
        card.add(lblHarga);
        card.add(Box.createVerticalStrut(5));
        card.add(lblKet);
        card.add(Box.createVerticalStrut(10));

        menuPanel.add(card);
    }
    
    private void showDetailDialog(Menu m) {
        // Kirim data menu ke Dialog
        MenuDetailDialog dialog = new MenuDetailDialog(this, m.getName(), m.getPrice(), m.getDescription());
        dialog.setVisible(true);

        if (dialog.isConfirmed) {
            String details = dialog.selectedSize + ", " + dialog.selectedSugar + ", " + dialog.selectedIce;
            if(dialog.isTumbler) details += " (Tumbler)";
            
            // Masukkan ke List Keranjang (Pakai Model CartItem)
            cartList.add(new CartItem(
                m.getId(), // ID
                m.getName(),               // Nama
                details,                   // Detail
                dialog.finalPrice,         // Harga Final
                dialog.selectedNote        // Catatan
            ));
            
            updateCartUI();
        }
    }
    
    private void updateCartUI() {
        keranjangPanel.removeAll();
        grandTotal = 0;

        for (int i = 0; i < cartList.size(); i++) {
            CartItem item = cartList.get(i);
            int idx = i;

            JPanel itemPanel = new JPanel(new BorderLayout());
            itemPanel.setMaximumSize(new Dimension(300, 50));
            itemPanel.setBackground(Color.WHITE);
            itemPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY));

            // Tampilan Info Item
            JLabel lblInfo = new JLabel("<html><b>" + item.getNamaMenu() + "</b><br><small>" + item.getDetail() + "</small></html>");
            lblInfo.setBorder(new EmptyBorder(5, 5, 5, 0));
            
            JPanel rightPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            rightPanel.setBackground(Color.WHITE);
            JLabel lblHarga = new JLabel("Rp " + (int)item.getHarga());
            
            JButton btnDel = new JButton("X");
            btnDel.setBackground(Color.RED);
            btnDel.setForeground(Color.WHITE);
            btnDel.setMargin(new Insets(2, 5, 2, 5));
            btnDel.setFont(new Font("Arial", Font.BOLD, 10));
            
            btnDel.addActionListener(e -> {
                cartList.remove(idx);
                updateCartUI();
            });
            
            rightPanel.add(lblHarga);
            rightPanel.add(btnDel);

            itemPanel.add(lblInfo, BorderLayout.CENTER);
            itemPanel.add(rightPanel, BorderLayout.EAST);
            keranjangPanel.add(itemPanel);
            
            grandTotal += item.getHarga();
        }
        
        totalLable.setText("Total: Rp " + (int)grandTotal);
        keranjangPanel.revalidate();
        keranjangPanel.repaint();
    }
    
    private void bungkusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bungkusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bungkusComboBoxActionPerformed

    private void bayarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarButtonActionPerformed
        // TODO add your handling code here:
        if (cartList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Keranjang kosong!");
            return;
        }
        if (namaField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi nama pemesan!");
            return;
        }

        String tipe = (String) bungkusComboBox.getSelectedItem();
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Total: Rp " + (int)grandTotal + "\nLanjutkan?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // PANGGIL CONTROLLER UNTUK PROSES TRANSAKSI
            // View tidak peduli bagaimana caranya disimpan, dia cuma terima hasil sukses/gagal
            boolean sukses = orderController.processCheckout(idCabang, namaField.getText(), tipe, grandTotal, cartList);
            
            if (sukses) {
                JOptionPane.showMessageDialog(this, "Pesanan Berhasil!");
                cartList.clear();
                updateCartUI();
                namaField.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memproses pesanan.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bayarButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        if (!cartList.isEmpty()) {
            int jawab = javax.swing.JOptionPane.showConfirmDialog(this, 
                    "Keranjang belanja masih terisi.\nJika kembali, pesanan akan hilang.\nApakah Anda yakin?", 
                    "Konfirmasi Kembali", 
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            
            if (jawab != javax.swing.JOptionPane.YES_OPTION) {
                return; 
            }
        }

        new view.landingPage().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarButton;
    private javax.swing.JComboBox<String> bungkusComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JPanel keranjangPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel totalLable;
    // End of variables declaration//GEN-END:variables
}
